package api.implementation;

/**
 * Enumeração que refere-se ao tipo de ordenação a ser aplicado
 */
public enum SortType
{
    PORTALS_ID, PORTALS_ENERGY, PORTALS_ENERGYMAX,
    CONNECTORS_ID, CONNECTORS_ENERGY, PORTALS_COOLDOWN,
    PLAYERS_TEAM, PLAYERS_LEVEL, PLAYERS_XP, PLAYERS_ENERGY, PLAYERS_ENERGYMAX, PLAYERS_CONQUEREDPORTALS,
    ROUTES_WEIGHT
}
